package semi.ad.cal;

import javax.swing.JFrame;

/**
 *
 * @author Acer
 */
public class semiadcal extends javax.swing.JFrame {

    /**
     * Creates new form semiadcal
     */
    public semiadcal() {
        initComponents();
    }
///gwugad
    double firstnum;
    double secondnum;
    double result;
    int count = 1;
    String operations;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keys = new javax.swing.JPanel();
        nine_button = new javax.swing.JButton();
        eight_button = new javax.swing.JButton();
        tan_button = new javax.swing.JButton();
        equal_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        zero_button = new javax.swing.JButton();
        power_button = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        square_root_button = new javax.swing.JButton();
        five_button = new javax.swing.JButton();
        subtract_button = new javax.swing.JButton();
        negate_button = new javax.swing.JButton();
        seven_button = new javax.swing.JButton();
        two_button = new javax.swing.JButton();
        four_button = new javax.swing.JButton();
        sin_button = new javax.swing.JButton();
        modulo_button = new javax.swing.JButton();
        decimal_button = new javax.swing.JButton();
        one_button = new javax.swing.JButton();
        six_button = new javax.swing.JButton();
        cos_button = new javax.swing.JButton();
        three_button = new javax.swing.JButton();
        divide_button = new javax.swing.JButton();
        multiply_button = new javax.swing.JButton();
        display = new javax.swing.JPanel();
        fulldisplay = new javax.swing.JTextField();
        partialdisplay = new javax.swing.JTextField();
        Quad_button = new javax.swing.JButton();
        facto_button = new javax.swing.JButton();
        area_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SemiAdvanceCalculator");
        setResizable(false);

        nine_button.setText("9");
        nine_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine_buttonActionPerformed(evt);
            }
        });

        eight_button.setLabel("8");
        eight_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eight_buttonActionPerformed(evt);
            }
        });

        tan_button.setText("tan");
        tan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tan_buttonActionPerformed(evt);
            }
        });

        equal_button.setText("=");
        equal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equal_buttonActionPerformed(evt);
            }
        });

        add_button.setText("+");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        zero_button.setText("0");
        zero_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_buttonActionPerformed(evt);
            }
        });

        power_button.setText("^");
        power_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                power_buttonActionPerformed(evt);
            }
        });

        clear_button.setText("C");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        square_root_button.setText("√");
        square_root_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_root_buttonActionPerformed(evt);
            }
        });

        five_button.setText("5");
        five_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_buttonActionPerformed(evt);
            }
        });

        subtract_button.setText("-");
        subtract_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtract_buttonActionPerformed(evt);
            }
        });

        negate_button.setText("+/-");
        negate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negate_buttonActionPerformed(evt);
            }
        });

        seven_button.setText("7");
        seven_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_buttonActionPerformed(evt);
            }
        });

        two_button.setText("2");
        two_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_buttonActionPerformed(evt);
            }
        });

        four_button.setText("4");
        four_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_buttonActionPerformed(evt);
            }
        });

        sin_button.setText("sin");
        sin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sin_buttonActionPerformed(evt);
            }
        });

        modulo_button.setText("%");
        modulo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulo_buttonActionPerformed(evt);
            }
        });

        decimal_button.setText(".");
        decimal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimal_buttonActionPerformed(evt);
            }
        });

        one_button.setText("1");
        one_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_buttonActionPerformed(evt);
            }
        });

        six_button.setText("6");
        six_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_buttonActionPerformed(evt);
            }
        });

        cos_button.setText("cos");
        cos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cos_buttonActionPerformed(evt);
            }
        });

        three_button.setText("3");
        three_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_buttonActionPerformed(evt);
            }
        });

        divide_button.setText("÷");
        divide_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divide_buttonActionPerformed(evt);
            }
        });

        multiply_button.setText("x");
        multiply_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiply_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout keysLayout = new javax.swing.GroupLayout(keys);
        keys.setLayout(keysLayout);
        keysLayout.setHorizontalGroup(
                keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(keysLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(four_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(seven_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(modulo_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sin_button, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                        .addComponent(one_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(negate_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(two_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(five_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(eight_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(square_root_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cos_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                        .addComponent(zero_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addGroup(keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(three_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(six_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nine_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(power_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tan_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                        .addComponent(decimal_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addGroup(keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(subtract_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(multiply_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(divide_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clear_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                        .addComponent(equal_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15))
        );
        keysLayout.setVerticalGroup(
                keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(keysLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(keysLayout.createSequentialGroup()
                                                        .addComponent(sin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(modulo_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(seven_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(four_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(one_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(negate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(keysLayout.createSequentialGroup()
                                                        .addComponent(cos_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(square_root_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(eight_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(five_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(two_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(zero_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(keysLayout.createSequentialGroup()
                                                        .addComponent(tan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(power_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(nine_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(six_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(three_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(decimal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(keysLayout.createSequentialGroup()
                                                .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(divide_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(multiply_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(subtract_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(equal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        fulldisplay.setEditable(false);
        fulldisplay.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fulldisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fulldisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fulldisplayActionPerformed(evt);
            }
        });

        partialdisplay.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        partialdisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        partialdisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partialdisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
                displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(displayLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(partialdisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                        .addComponent(fulldisplay))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayLayout.setVerticalGroup(
                displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(displayLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(fulldisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(partialdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        Quad_button.setText("Quadratic");
        Quad_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quad_buttonActionPerformed(evt);
            }
        });

        facto_button.setText("Factorial");
        facto_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facto_buttonActionPerformed(evt);
            }
        });

        area_button.setText("Area");
        area_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(keys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(Quad_button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(facto_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(area_button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Quad_button)
                                        .addComponent(facto_button)
                                        .addComponent(area_button))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(keys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void partialdisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partialdisplayActionPerformed
        partialdisplay.setText("");
    }//GEN-LAST:event_partialdisplayActionPerformed

    private void fulldisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fulldisplayActionPerformed
        fulldisplay.setText("");
    }//GEN-LAST:event_fulldisplayActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        partialdisplay.setText("");
        fulldisplay.setText("");
        firstnum = 0;
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void zero_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_buttonActionPerformed
        //String Enternumber = partialdisplay.getText()+zero_button.getText();
        partialdisplay.setText(partialdisplay.getText() + "0");
        fulldisplay.setText(fulldisplay.getText() + "0");
    }//GEN-LAST:event_zero_buttonActionPerformed

    private void one_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_buttonActionPerformed
        //String Enternumber = partialdisplay.getText()+one_button.getText();
        partialdisplay.setText(partialdisplay.getText() + "1");
        fulldisplay.setText(fulldisplay.getText() + "1");
    }//GEN-LAST:event_one_buttonActionPerformed

    private void two_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_buttonActionPerformed
        //String Enternumber = partialdisplay.getText()+two_button.getText();
        partialdisplay.setText(partialdisplay.getText() + "2");
        fulldisplay.setText(fulldisplay.getText() + "2");
    }//GEN-LAST:event_two_buttonActionPerformed

    private void three_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_buttonActionPerformed
        //String Enternumber = partialdisplay.getText()+three_button.getText();
        partialdisplay.setText(partialdisplay.getText() + "3");
        fulldisplay.setText(fulldisplay.getText() + "3");
    }//GEN-LAST:event_three_buttonActionPerformed

    private void four_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_buttonActionPerformed
        //String Enternumber = partialdisplay.getText()+four_button.getText();
        partialdisplay.setText(partialdisplay.getText() + "4");
        fulldisplay.setText(fulldisplay.getText() + "4");
    }//GEN-LAST:event_four_buttonActionPerformed

    private void five_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_buttonActionPerformed
        // String Enternumber = partialdisplay.getText()+five_button.getText();
        partialdisplay.setText(partialdisplay.getText() + "5");
        fulldisplay.setText(fulldisplay.getText() + "5");
    }//GEN-LAST:event_five_buttonActionPerformed

    private void six_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_buttonActionPerformed
        //String Enternumber = partialdisplay.getText()+six_button.getText();
        partialdisplay.setText(partialdisplay.getText() + "6");
        fulldisplay.setText(fulldisplay.getText() + "6");
    }//GEN-LAST:event_six_buttonActionPerformed

    private void seven_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_buttonActionPerformed
        //String Enternumber = partialdisplay.getText()+seven_button.getText();
        partialdisplay.setText(partialdisplay.getText() + "7");
        fulldisplay.setText(fulldisplay.getText() + "7");
    }//GEN-LAST:event_seven_buttonActionPerformed

    private void eight_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eight_buttonActionPerformed
        //String Enternumber = partialdisplay.getText()+eight_button.getText();
        partialdisplay.setText(partialdisplay.getText() + "8");
        fulldisplay.setText(fulldisplay.getText() + "8");
    }//GEN-LAST:event_eight_buttonActionPerformed

    private void nine_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine_buttonActionPerformed
        //String Enternumber = partialdisplay.getText()+nine_button.getText();
        partialdisplay.setText(partialdisplay.getText() + "9");
        fulldisplay.setText(fulldisplay.getText() + "9");
    }//GEN-LAST:event_nine_buttonActionPerformed

    private void negate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negate_buttonActionPerformed
        firstnum = Double.parseDouble(partialdisplay.getText());
        double negate = -firstnum;
        fulldisplay.setText("-(" + fulldisplay.getText() + ")");
        partialdisplay.setText("" + negate);
    }//GEN-LAST:event_negate_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        secondnum = Double.parseDouble(partialdisplay.getText());
        firstnum = firstnum + secondnum;
        fulldisplay.setText(fulldisplay.getText() + "+");
        partialdisplay.setText("");
        operations = "+";
    }//GEN-LAST:event_add_buttonActionPerformed

    private void subtract_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtract_buttonActionPerformed
        secondnum = Double.parseDouble(partialdisplay.getText());
        firstnum = firstnum + secondnum;
        fulldisplay.setText(fulldisplay.getText() + "-");
        partialdisplay.setText("");
        operations = "-";
    }//GEN-LAST:event_subtract_buttonActionPerformed

    private void multiply_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiply_buttonActionPerformed
        secondnum = Double.parseDouble(partialdisplay.getText());
        firstnum = firstnum + secondnum;
        fulldisplay.setText(fulldisplay.getText() + "x");
        partialdisplay.setText("");
        operations = "x";
    }//GEN-LAST:event_multiply_buttonActionPerformed

    private void divide_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divide_buttonActionPerformed
        secondnum = Double.parseDouble(partialdisplay.getText());
        firstnum = firstnum + secondnum;
        fulldisplay.setText(fulldisplay.getText() + "÷");
        partialdisplay.setText("");
        operations = "÷";
    }//GEN-LAST:event_divide_buttonActionPerformed

    private void power_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_power_buttonActionPerformed
        firstnum = Double.parseDouble(partialdisplay.getText());
        fulldisplay.setText(fulldisplay.getText() + "^");
        partialdisplay.setText("");
        operations = "^";
    }//GEN-LAST:event_power_buttonActionPerformed

    private void square_root_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_root_buttonActionPerformed
        firstnum = Double.parseDouble(partialdisplay.getText());
        double sqrt = Math.sqrt(firstnum);
        fulldisplay.setText("√(" + fulldisplay.getText() + ")");
        partialdisplay.setText("" + sqrt);

    }//GEN-LAST:event_square_root_buttonActionPerformed

    private void modulo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulo_buttonActionPerformed
        firstnum = Double.parseDouble(partialdisplay.getText());
        fulldisplay.setText(fulldisplay.getText() + "%");
        partialdisplay.setText("");
        operations = "%";
    }//GEN-LAST:event_modulo_buttonActionPerformed

    private void sin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sin_buttonActionPerformed
        firstnum = Double.parseDouble(partialdisplay.getText());
        double sin = Math.sin(firstnum);
        fulldisplay.setText("sin(" + fulldisplay.getText() + ")");
        partialdisplay.setText("" + sin);
    }//GEN-LAST:event_sin_buttonActionPerformed

    private void cos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cos_buttonActionPerformed
        firstnum = Double.parseDouble(partialdisplay.getText());
        double cos = Math.cos(firstnum);
        fulldisplay.setText("cos(" + fulldisplay.getText() + ")");
        partialdisplay.setText("" + cos);
    }//GEN-LAST:event_cos_buttonActionPerformed

    private void tan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tan_buttonActionPerformed
        firstnum = Double.parseDouble(partialdisplay.getText());
        double tan = Math.tan(firstnum);
        fulldisplay.setText("tan(" + fulldisplay.getText() + ")");
        partialdisplay.setText("" + tan);
    }//GEN-LAST:event_tan_buttonActionPerformed

    private void decimal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimal_buttonActionPerformed
        //String Enternumber = partialdisplay.getText()+nine_button.getText();
        partialdisplay.setText(partialdisplay.getText() + ".");
        fulldisplay.setText(fulldisplay.getText() + ".");
    }//GEN-LAST:event_decimal_buttonActionPerformed

    private void equal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equal_buttonActionPerformed
        secondnum = Double.parseDouble(partialdisplay.getText());
        if (operations.equals("+")) {
            result = firstnum + secondnum;
        }
        if (operations.equals("-")) {
            result = firstnum - secondnum;
        }
        if (operations.equals("x")) {
            result = firstnum * secondnum;
        }
        if (operations.equals("÷")) {
            result = firstnum / secondnum;
        }
        if (operations.equals("^")) {
            result = Math.pow(firstnum, secondnum);
        }
        if (operations.equals("%")) {
            result = firstnum % secondnum;
        }
        /*
        if(operations.equals("|"))
            result = (firstnum+secondnum)/(count);
         */

        partialdisplay.setText(result + "");
        fulldisplay.setText("" + result);
        firstnum = 0;
        count = 1;
    }//GEN-LAST:event_equal_buttonActionPerformed

    private void area_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mode_buttonActionPerformed
        setVisible(false);
        areacal ar = new areacal();
        ar.setVisible(true);
        ar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_mode_buttonActionPerformed

    private void facto_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_median_buttonActionPerformed
        setVisible(false);
        NewJFrame solve = new NewJFrame();
        solve.setVisible(true);
        solve.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_median_buttonActionPerformed

    private void Quad_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mean_buttonActionPerformed
        setVisible(false);
        quadratic qd = new quadratic();
        qd.setVisible(true);
        qd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        /*
        secondnum = Double.parseDouble(partialdisplay.getText());
        firstnum = firstnum + secondnum;
        fulldisplay.setText(fulldisplay.getText()+"|");
        partialdisplay.setText("");
        operations = "|";
        count = count+1;
         */
    }//GEN-LAST:event_Mean_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(semiadcal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(semiadcal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(semiadcal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(semiadcal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new semiadcal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Quad_button;
    private javax.swing.JButton add_button;
    private javax.swing.JButton clear_button;
    private javax.swing.JButton cos_button;
    private javax.swing.JButton decimal_button;
    private javax.swing.JPanel display;
    private javax.swing.JButton divide_button;
    private javax.swing.JButton eight_button;
    private javax.swing.JButton equal_button;
    private javax.swing.JButton five_button;
    private javax.swing.JButton four_button;
    private javax.swing.JTextField fulldisplay;
    private javax.swing.JPanel keys;
    private javax.swing.JButton facto_button;
    private javax.swing.JButton area_button;
    private javax.swing.JButton modulo_button;
    private javax.swing.JButton multiply_button;
    private javax.swing.JButton negate_button;
    private javax.swing.JButton nine_button;
    private javax.swing.JButton one_button;
    private javax.swing.JTextField partialdisplay;
    private javax.swing.JButton power_button;
    private javax.swing.JButton seven_button;
    private javax.swing.JButton sin_button;
    private javax.swing.JButton six_button;
    private javax.swing.JButton square_root_button;
    private javax.swing.JButton subtract_button;
    private javax.swing.JButton tan_button;
    private javax.swing.JButton three_button;
    private javax.swing.JButton two_button;
    private javax.swing.JButton zero_button;
    // End of variables declaration//GEN-END:variables
}
